### ISSUE TITLE
迅雷看看字幕下载失败

### ISSUE THREAD

**Issue by beermedlar** [91270/Emby.MeiamSub#10]
![image](https://user-images.githubusercontent.com/32614465/129202084-bd2b095b-0684-410b-a0d9-fb57d69c4999.png)

显示连接超时，但是无论是电脑直接请求该地址或者通过docker exec进入到emby所在的容器直接wget该地址都是正常的。

**Comment by beermedlar** [comment]
> 你的线路是国内还是国外的

国外，自动分流的

**Comment by 91270** [comment]
> > 你的线路是国内还是国外的
> 
> 国外，自动分流的

服务器是不是有 IPV6 ，可以修改 HOSTS 文件 强制解析到 IPV6 上
