### ISSUE TITLE
这个怎么安装？是全部文件都复制进去还是哪个文件？没搞懂。

### ISSUE THREAD

**Issue by chjshi** [91270/Emby.MeiamSub#12]
这个怎么安装？是全部文件都复制进去还是哪个文件？没搞懂。

**Comment by 91270** [comment]
你复制的应该是源代码，复制的文件应该是编译好的 .dll 文件

可以通过 releases 标签下载最新编译好的版本进行安装

https://github.com/91270/Emby.MeiamSub/releases/download/v1.0.2.0/Emby.MeiamSub.zip

**Comment by chjshi** [comment]
太感谢了。找这个字幕的东西找了好久没找到，下载这个复制过去就可以了。感觉解答，不过建议在说明里面写上，，不然对我们这些小白来说真的是一头雾水。
