### ISSUE TITLE
我的 emby 装在 centos 上的，我该怎么使用呢

### ISSUE THREAD

**Issue by kaaaaai** [91270/Emby.MeiamSub#16]
插件我都移到对应的目录了，但重启后在 emby 的插件界面也看到 MediaSub.Thunder 名称的插件了。

但我该怎么使用呢，播放电影时仍旧没有中文字幕出现，是不是要想 opensub 那样手动搜索下载，或者进行其他配置？

**Comment by 91270** [comment]
参考说明
