### ISSUE TITLE
WINDOWS 4.6.4.0应该怎么安装，没有发现文档中提到的目录

### ISSUE THREAD

**Issue by bluegua** [91270/Emby.MeiamSub#21]
RT所说。

**Comment by bluegua** [comment]
已经找到了，C:\Users\{user name}\AppData\Roaming\Emby-Server
插件已经放进去了，EMBY也重启了，怎么使用呢？怎么知道有没有安装成功呢

**Comment by 91270** [comment]
查看文档说明
