### ISSUE TITLE
win10  X64  emby版本4.6.4.0  不停下载同一个字幕

### ISSUE THREAD

**Issue by yysudp** [91270/Emby.MeiamSub#22]
win10  X64  emby版本4.6.4.0  不停下载同一个字幕      

- [ ] 不关掉就会不停下载 #     发现的时候已经下载了200多个同样的字幕在同个电影文件夹下面  电视剧文件夹一样

**Comment by lukaschan** [comment]
https://github.com/91270/Emby.MeiamSub/issues/23
