### ISSUE TITLE
可否设置为按需搜索下载字幕

### ISSUE THREAD

**Issue by lukaschan** [91270/Emby.MeiamSub#23]
emby的opensubtitles插件是用户按需搜索字幕。我发现您开发的插件是自己后台自动下载字幕，且我发现很多影视里面自动下载字幕达上百个，也就是重复下载字幕。
所以，能否设置为按需手动下载？

**Comment by 91270** [comment]
你试下，不要启用插件勾选。手动搜索应该也会使用插件的

**Comment by lukaschan** [comment]
> 你试下，不要启用插件勾选。手动搜索应该也会使用插件的

媒体库的文件夹设置中不勾选启用插件吗？
之前发现每个影片后台已经自动下载了上百个重复字幕，还花了大力气才清理掉嘿嘿。

**Comment by lukaschan** [comment]
> > 你试下，不要启用插件勾选。手动搜索应该也会使用插件的
> 
> 媒体库的文件夹设置中不勾选启用插件吗？ <img alt="Screen Shot 2021-11-13 at 7 29 15 PM" width="1119" src="https://user-images.githubusercontent.com/3959525/141642164-fcd39a8d-dca9-46c5-a811-b966116abc67.png">
> 
> 之前发现每个影片后台已经自动下载了上百个重复字幕，还花了大力气才清理掉嘿嘿。

实测：媒体库不勾选插件，具体影片中手动搜索可以启用插件。👍！

<img width="936" alt="Screen Shot 2021-11-14 at 8 10 37 PM" src="https://user-images.githubusercontent.com/3959525/141680495-1d0c1b5c-c890-481e-88cf-96c1d3450c5c.png">

**Comment by x91270** [comment]
重复下载的原因。可能是因为文件命令的问题，我刮削过的不会
