### ISSUE TITLE
无法下载字幕 有错误提示

### ISSUE THREAD

**Issue by gx19970920** [91270/Emby.MeiamSub#24]
Could not load file or assembly System.Net.Requests,Version=4.1.2.0,Culture=neutral,PublicKeyToken=b03f5f7f11d50a3a'.The system cannot open the file.(0x80070004)

![image](https://user-images.githubusercontent.com/33535925/143965287-0e93f124-c9d1-4921-8874-d3e45e9ad300.png)

**Comment by x91270** [comment]
什么版本的 Emby

**Comment by gx19970920** [comment]
4.6.6.0

**Comment by x91270** [comment]
相同版本。我这边没这个问题啊

**Comment by gx19970920** [comment]
您好，我觉得应该是中文命名的问题，英文命名的电影没这个问题
