### ISSUE TITLE
我该如何设置才能做到按需下载字幕？而不是自动下载

### ISSUE THREAD

**Issue by SelfEnough** [91270/Emby.MeiamSub#28]
我在媒体库 - 字幕中设置勾选了这个插件提供的两个字幕源，在字幕语言 选择了Chinese
但是每次有新的电影加入emby 随着扫描加入，插件会自动工作自动下载字幕。（embylog里可以看到随着新媒体扫描入库会直接触发插件搜索下载字幕，）
这个本意是好的，但是因为射手和迅雷的字幕库本身不佳，加上最新的字幕基本没有，导致自动下了一堆没用的不匹配的垃圾字幕。
希望每次有视频文件加入emby扫描的时候 ，不要运行字幕搜索下载，
简单说就是不要自动下字幕。
而是我今天想看这部片了，打开，发现没字幕。这个时候，我再自己手动搜。让我自己甄别搜索结果再按需下载。

**Comment by louis000008** [comment]
设置媒体库  字幕下载  下面的勾全勾掉 就行了！

**Comment by 91270** [comment]
去掉勾选
