### ISSUE TITLE
不懂就问：emby添加插件成功后，除了重启还需要其他什么操作吗？

### ISSUE THREAD

**Issue by kklod** [91270/Emby.MeiamSub#33]
![image](https://user-images.githubusercontent.com/50442661/150927397-688207dd-c588-4f96-aff9-5cad8a846b67.png)

插件安装好了，但是播放时仍然没有字幕...

**Comment by TwinsenLiang** [comment]
重启服务后在媒体库里面设定，然后再去到具体的影片里面搜索。
