### ISSUE TITLE
想请问一下添加插件问题

### ISSUE THREAD

**Issue by BeauChu** [91270/Emby.MeiamSub#4]
LINUX
复制插件文件到  /opt/emby-server/system/plugins
复制插件文件到  /var/lib/emby/plugins
重启服务

想问一下是直接下载下来整个文件夹直接复制到这个目录下吗还是单独下载哪个文件。。
下载下来放进去会自动匹配到插件库里吗还是要安装一下。
抱歉我是个小白不太懂这个

**Comment by CowBug** [comment]
直接把两个 插件放在plugins里面就行

**Comment by CowBug** [comment]
> LINUX
> 复制插件文件到 /opt/emby-server/system/plugins
> 复制插件文件到 /var/lib/emby/plugins
> 重启服务
> 
> 想问一下是直接下载下来整个文件夹直接复制到这个目录下吗还是单独下载哪个文件。。
> 下载下来放进去会自动匹配到插件库里吗还是要安装一下。
> 抱歉我是个小白不太懂这个



> LINUX
> 复制插件文件到 /opt/emby-server/system/plugins
> 复制插件文件到 /var/lib/emby/plugins
> 重启服务
> 
> 想问一下是直接下载下来整个文件夹直接复制到这个目录下吗还是单独下载哪个文件。。
> 下载下来放进去会自动匹配到插件库里吗还是要安装一下。
> 抱歉我是个小白不太懂这个

直接把两个 插件放在plugins里面就行

**Comment by CowBug** [comment]
> LINUX
> 复制插件文件到 /opt/emby-server/system/plugins
> 复制插件文件到 /var/lib/emby/plugins
> 重启服务
> 
> 想问一下是直接下载下来整个文件夹直接复制到这个目录下吗还是单独下载哪个文件。。
> 下载下来放进去会自动匹配到插件库里吗还是要安装一下。
> 抱歉我是个小白不太懂这个

直接把两个 插件放在plugins里面就行

**Comment by romanticgrass** [comment]
这个插件在威联通套件版里面能用吗,我看了下没有这个文件夹,找到一个全是dll格式的插件,楼主发的又没有看到dll的格式的

**Comment by 91270** [comment]
> 这个插件在威联通套件版里面能用吗,我看了下没有这个文件夹,找到一个全是dll格式的插件,楼主发的又没有看到dll的格式的

https://github.com/91270/Emby.MeiamSub/releases/download/v1.0.2.0/Emby.MeiamSub.zip

这不是编译好的 dll 格式的么

**Comment by 91270** [comment]
> 想问一下是直接下载下来整个文件夹直接复制到这个目录下吗还是单独下载哪个文件。。
> 下载下来放进去会自动匹配到插件库里吗还是要安装一下。
> 抱歉我是个小白不太懂这个

在项目的  [Releases](https://github.com/91270/Emby.MeiamSub/releases) 目录中 下载已编译好的文件进行安装

**Comment by romanticgrass** [comment]
谢谢
