### ISSUE TITLE
视频有多版本的话，下载的字幕永远是第一个版本的命名

### ISSUE THREAD

**Issue by SelfEnough** [91270/Emby.MeiamSub#6]
比如视频有3个版本 

1. Black.Widow.2021.1080p.mkv
2. Black.Widow.2021.2160p.mkv
3. Black.Widow.2021.2160p.Remux.mkv

第一个视频可能我已经有字幕了，想看第二个2160P的版本，发现没有字幕，
于是我切换到第二个视频版本，选择字幕下载
搜索是正常的，可以搜索到。
但是下载后，字幕文件的命名是
**Black.Widow.2021.1080p.srt**
问题就来了，虽然我是按照第二个视频搜索的，但是命名依旧是第一个视频，
相当于是给第一个视频下了字幕，第二个视频依旧没有字幕。

**Comment by 91270** [comment]
回头我测试下，我如果三个视频文件，在目录的显示的时候是一个 视频，还是三个视频

**Comment by SelfEnough** [comment]
> 回头我测试下，我如果三个视频文件，在目录的显示的时候是一个 视频，还是三个视频
目录默认是显示第一个版本，
![image](https://user-images.githubusercontent.com/36906472/126023295-abe95c2f-a5da-4a26-93b4-1bf182d0479a.png)

点击视频版本下拉后，可以看到所有版本，并切换选择
![image](https://user-images.githubusercontent.com/36906472/126023339-6f32579e-1f6e-4ba9-925e-c360b29c8a54.png)
然后就会出现上面的问题，不管选哪个版本搜索字幕，下载到的依旧是第一个版本的命名。

文件夹内结构是这样的

///movies
//////Black Widow(2021)
////////////Black.Widow.2021.1080p.mkv
////////////Black.Widow.2021.2160p.mkv
////////////Black.Widow.2021.2160p.Remux.mkv

**Comment by 91270** [comment]
你试一下，选中对应的视频，然后手动下载字幕试试

**Comment by SelfEnough** [comment]
> 你试一下，选中对应的视频，然后手动下载字幕试试

对，我就是这么操作的，依旧会出现这个问题

**Comment by 91270** [comment]
有时间我看一下，文件名理论上是根据视频文件来的， Emby 有个 API 获取的。我看看是否能解决

**Comment by SelfEnough** [comment]
> 有时间我看一下，文件名理论上是根据视频文件来的， Emby 有个 API 获取的。我看看是否能解决

ღ( ´･ᴗ･` )比心
