### ISSUE TITLE
东西确实是好,很多岛国电影部分也配上了字幕

### ISSUE THREAD

**Issue by 277383761** [91270/Emby.MeiamSub#8]
但也要说说它的缺点
1.有些视频字幕帮我自动下载了25个都有
2.一直在后台下载字幕,使的硬盘没的休息
3.无法下载到字幕的视频,还是会反复的去扫它并尝试下载.这点挺不友好.
希望作者出点好的方案解决一下

**Comment by 91270** [comment]
目前自动下载的功能，是 Emby 自动触发的。 你看下这里的设置，是否可以控制。

我在去看看官方的文档，看有没有相关的说明

**Comment by 91270** [comment]
![image](https://user-images.githubusercontent.com/61639203/126508884-d23c8b30-7fda-4142-af3e-f8e6a257b1cf.png)

另外你目前服务端使用的是那个，官方最新的版本 BUG 修复中有提到重复下载字幕的问题

**Comment by 277383761** [comment]
好的,我设置成了每周一次,然后每次给个1小时..差不多了.因为大部分字幕能下载的早就下过来了,下不了的始终下不了
它连续下载有些视频有30多个序列,请问这能不能解决.

**Comment by 277383761** [comment]
如果实在没有办法,我还是建议弄一个开关吧,全盘扫描生成字幕.以后全部用手动方案搜索字幕

**Comment by 91270** [comment]
你现在服务端用的是那个版本，我这边好像不会重复下载的

**Comment by 277383761** [comment]
> 你现在服务端用的是那个版本，我这边好像不会重复下载的

是emby 4.6.3版本,你用的是哪个版本?

**Comment by 91270** [comment]
![image](https://user-images.githubusercontent.com/61639203/126655963-3a2dc79d-ddd2-435a-b59e-083b4daa7ec3.png)

这里不要勾选语言，试试

**Comment by 277383761** [comment]
现在已经更新到4.6.4版本了,但是不敢装这个插件了,昨天清理字幕都弄了一下午,希望作者弄成手动搜索下载字幕会不会更好?

**Comment by 91270** [comment]
我现在的设置，就是没有你这样的问题。不会重复下载。只有在新增加影片时，才会下载一次

这是我的设置

![image](https://user-images.githubusercontent.com/61639203/126730474-741267e1-6cea-448e-b855-5d4cdaf5e2a5.png)

**Comment by Ozzy-hzy** [comment]
![image](https://user-images.githubusercontent.com/48149261/127267129-bdf13d4a-754f-49b5-97bd-a1801ebd0a03.png)
确实会重复下，而且都是之前的，还是关了手动加字幕好
